### ISSUE TITLE
One song comes up many times

### ISSUE THREAD

**Issue by bevynfernandes** [josephbeattie/Fluent-Media-Player-Dev#76] opened 2021-12-04 18:42 UTC
I only have one of each song and yet it comes up many times.
Restarting the App has no difference

My song Files:
![explorer_dxsYDencyZ](https://user-images.githubusercontent.com/62027082/144720989-910a7d78-0331-4b02-844c-682520e0dbcf.png)

What comes up:

https://user-images.githubusercontent.com/62027082/144721032-f3d424bb-42b7-4d00-82a4-e1d65e5bfcaa.mp4

**Comment by itsWindows11** [comment] 2021-12-05 09:42
I guess this is a duplicate of #70, but I'm going to keep this issue

**Closed as completed** 2021-12-28 09:25 UTC
Labels: bug, duplicate
