### ISSUE TITLE
Crash upon lauch and during playback

### ISSUE THREAD

**Issue by ams-Firely** [josephbeattie/Fluent-Media-Player-Dev#97] opened 2021-12-31 12:10 UTC
//feedback
/* app occasionally crash upon launch or during music playback.
app also crash if flip back-to-back between "All Videos" tab with other tabs.
Video list doesn't show anything in  both Pre-alpha 3 and Pre-alpha 4 indev.

*/

//error log starts here

The exception System.NullReferenceException happened last time the app was launched.

Stack trace:
Object reference not set to an instance of an object.
   at Rise.App.App.<OnSuspending>d__55.MoveNext() + 0x6e
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x21
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__7_0(Object) + 0x1e
   at System.Action`1.Invoke(T) + 0x28
   at System.Threading.WinRTSynchronizationContext.Invoker.InvokeCore() + 0x33

Source: 
HResult: -2147467261

//error log ends here

**Comment by ams-Firely** [comment] 2021-12-31 12:48
Version : Pre-Alpha 4 InDev! (v.0.0.135.0)

**Comment by josephbeattie** [comment] 2021-12-31 13:00
Theres a new build coming tomorrow! Let us know if this issue persists. 

Thanks, Joseph.

**Comment by itsWindows11** [comment] 2021-12-31 13:56
Issues like these would be fixed by reinstalling the app, I couldn't reproduce this issue.

**Closed as completed** 2022-01-14 09:28 UTC
Labels: invalid
